name: ✨ Feature Request
description: Suggest an idea for HearWell
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of the problem
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New Tool
        - Improvement to Existing Tool
        - UI/UX Enhancement
        - Accessibility
        - Translation/i18n
        - Documentation
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered

  - type: checkboxes
    id: willing-to-contribute
    attributes:
      label: Would you like to work on this?
      options:
        - label: I'm willing to submit a PR for this feature
          required: false
